/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaBoy;

import org.junit.Test;
import static org.junit.Assert.*;

public class JavaBoyTest {
    @Test public void testAppHasAGreeting() {
        JavaBoy classUnderTest = new JavaBoy();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
