/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaBoy;

import JavaBoy.cartridge.Cartridge;

import java.io.File;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Cartridge cart = new Cartridge(new File("/home/damilola/Downloads/DMG_ROM.bin"));
    }
}
